import Head from 'next/head'
import Image from 'next/image'
import Featured from '../components/Featured'
import styles from '../styles/Home.module.css'
import PizzaList from "../components/PizzaList";
import axios from 'axios';
import { useState } from 'react';
import AddButton from '../components/AddButton';
import Add from '../components/Add';


export default function Home({pizzaList, admin}) {

  const [close, setClose] = useState(true);
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Delvery app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Featured/>
      {admin ? <AddButton setClose={setClose} title={'Add product'}/> : <></>}
      <PizzaList pizzaList ={pizzaList}/>
      {!close && <Add setClose={setClose} />}
    </div>
  )
}

const BASE_URL = 'http://localhost:3000/api/';
export const publicRequest = axios.create({
  baseURL:BASE_URL
});


export const getServerSideProps = async (ctx) =>{

  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  console.log(admin)
  console.log(myCookie)

  const res = await publicRequest.get(`products`);
  return{
    props:{
      pizzaList:res.data,
      admin
    }
  }
}